INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Extra Virgin Oil', 'Масло Оливковое
');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Carte Noire Crema Delice ', 'Кофе Зерно');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Батон Нарезной', 'Хлеб');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Заводской', 'Хлеб');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Заводской', 'Хлеб');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Тостовый хлеб', 'Хлеб');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Пакет', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Духа океана', 'Крабовые палочки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Baker House', 'Пироженные');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('RenMilk 3.2 0.5л', 'Молоко');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Умка', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Рахат Шоколадка', 'Шоколад');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Тирамису 430гр', 'Торт');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сливочное мороженное 1кг', 'Мороженное');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Яйцо Кадомец 0 категория', 'Яйцо');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Пряник Круглый', 'Пряник');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Картофель', 'Картофель');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Урсосан 20шт', 'Лекарства');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Шпигачки Акнар', 'Шпигачки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сардельки Карагандинские Акнар', 'Сардельки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Грубная часть Акнар', 'Грудинка');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Dino шоколадные лапы', 'Готовый завтрак');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Мармелад в шоколаде', 'Конфеты');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сникерс', 'Шоколад');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('МагКалейдоскоп с маком', 'Крекер');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Северные', 'Пряник');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сухари Ванильные, Сельпром', 'Сухари');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Янтарные сладости', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Гречневая крупа', 'Крупа');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Кефир RenMilk 2.5% 0.5л', 'Кефир');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Андреевские', 'Сосиськи');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Прага', 'Пиво');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сардельки Карагандинские Акнар', 'Сардельки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Докторская ГОСТ Акнар ', 'Колбаса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Великокняжеский', 'Сыр');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Шпигачки в натуральной оболочке', 'Шпигачки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('пакет Магнум', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан колесики 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Белый кот ', 'Туаленая бумага');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Always Ultra 12шт', 'Прокладки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Old space "Space Capitan" 70мл', 'Дезодорант');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Рожки 12 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Лингвини 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Спагетти 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Улитка 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Соль Араптуз помол1 1кг', 'Соль');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Белгородские овощи 400гр в.с.', 'Кукуруза');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('капитан морей нат 250 гр', 'Сардинелла');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Рыбачка соня Антлантическая натуральная с добавлением масла 185гр', 'Скумбрия');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Рожки 8 400гр', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('сахар', 'Сахар');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Султан Спироль 400гр ', 'Макароны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Перец Almaty Spices 15гр', 'Чёрный молотый перец');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('USAMS для зарядки Type-C зеленый 2А 1.2M ', 'Кабель');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Бахус Казахстан 3 звезды 40% 0.5л', 'Коньяк');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Майское рафинированное 5л', 'Масло Подсолнечное');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('3 Желания провансаль 67% 800гр', 'Майонез');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Чёрный Жемчуг экстремальное увлажнение д/лица ночной', 'Крем');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Бонпари жевательный фруктовый 100гр', 'Мармелад');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хасанов снеж', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хасанов Овсяно-медовае', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Барбарис приправыч ягоды сушенные 25гр', 'Приправы');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Барские сладости кунжутные 150 гр', 'Козинак');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Топар тепличный ', 'Томат');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Невский кондитер картошка ', 'Конфеты');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хасанов крекер с июмом', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier увлажнение свежий взгляд 6гр', 'Патчи');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевые зел чай 6 гр', 'Патчи');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier увлажнение вокруг глас 6 гр', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая увлажнение 32гр', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая увлажнение', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier skin naturals тканевая д/лица', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая увлажнение', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая увлажение 32гр', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая гиалуронов 32гр', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Чёрный жемчуг питание', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Лесной бальзам 400мл', 'Ополаскиватель');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Pro series rep air (глубокое востановление) 500мл ', 'Шампунь');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Рахат шоколадно-ореховая 470гр', 'Паста');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('гречневая ', 'Крупа');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Чистая линия зел чай 400мл', 'Вода Мицеллярная');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('в клетку', 'Тетрадь');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('в линейку', 'Тетрадь');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Seliko деликатесный печеночный 100гр', 'Паштет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сибирский уксус 160гр', 'Кислота уксуса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Syoss 6 темно-руссый ', 'Краска для волос');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('для плова  15гр', 'Приправы');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Glamour Velou 120 den ', 'Колготки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Heinz итальянский', 'Кетчук');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('ОВ супер 8 шт', 'Тампоны');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хмели-сунели 20гр', 'Приправы');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Almaty spices острый молотый ', 'Приправы');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Фрекен Бок Хозяйственные перчатки', 'Перчатки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Деревня твороженная ', 'Творог');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Бисквит Orion Choco Pi 6шт', 'Печенье ');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Кусочки фруктовые ФрутоНяня', 'Пюре');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Агуша фруктовые овощные 90гр', 'Пюре');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Агуша яблоко-клубника с творогом', 'Пюре');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Кусочки фруктовые фрут няня ', 'Пюре');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Bon Pari со вкусом 90гр', 'Суфле');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Garnier тканевая очищающая уголь ', 'Маска');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Детские B-2107', 'Варежки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Бедро охлажденое', 'Курица');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Майка П/З', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Veiro', 'Туаленая бумага');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Полотенце', 'Plushe БигРолл');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('сэндвич "Супер-Конт"', 'Печенье');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Mr. Ricco Оливковый ', 'Майонез');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Подсолнечный 150гр', 'Козинак');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('БАРХАТ универсальные', 'Перчатки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Астория Асс 180 гр', 'Соус');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Mr.Ricco томатный ', 'Кетчук');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хоз. суперпрочные', 'Перчатки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Ванильная Донские сладости', 'Пастила ');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Хозяйственные ', 'Перчатки');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('FixPrice', 'Карта');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('майка Акнар', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('с картошкой 0.45кг Акнар', 'Вареники');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Алтын Балапан 0.9 кг', 'Пельмени');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Любимые с сыром', 'Пельмени');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('с капустой 0.45кг Акнар', 'Вареники');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Докторская ГОСТ ', 'Колбаса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('куринный охл Акнар', 'Фарш');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('слоенно дрожевое 0.9 кг', 'Тесто');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Докторская ГОСТ', 'Колбаса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Прослойка по домашнему', 'Сало');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Шея копченая', 'Мясо');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('майка "Акнар"', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('майка "Акнар"', 'Пакет');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('куриный Охл', 'Фарш');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('слоеное дрожевое 0.9 кг', 'Тесто');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Русская в синюге', 'Колбаса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Окорочек тушки охл Акнар', 'Курица');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Докторская ГОСТ', 'Колбаса');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Грудная часть тушки охл Акнар', 'Курица');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Каспийские 0.9', 'Манты');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Сочные 0.9кг', 'Пельмени');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('Арман 0.9кг', 'Пельмени');
INSERT INTO "main"."ProductNames" ("productName", "ProductCategoriaName") VALUES ('с капустой 0.45 кг', 'Вареники');